[package]
name = "mobibike-data-collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde_json = "1.0.109"
chrono = "0.4.41"
